# Image Transfer - As The Controller Device
#
# This script is meant to talk to the "image_transfer_jpg_streaming_as_the_remote_device_for_your_computer.py" on the OpenMV Cam.
#
# This script shows off how to transfer the frame buffer to your computer as a jpeg image.

import io, pygame, rpc, serial, serial.tools.list_ports, socket, sys, time
from PIL import Image, ImageOps
import numpy as np
from widgets import *
import unikostyl

# Fix Python 2.x.
try: input = raw_input
except NameError: pass

# The RPC library above is installed on your OpenMV Cam and provides multiple classes for
# allowing your OpenMV Cam to control over USB or WIFI.

##############################################################
# Choose the interface you wish to control an OpenMV Cam over.
##############################################################

# Uncomment the below lines to setup your OpenMV Cam for controlling over a USB VCP.
#
# * port - Serial Port Name.
#

port_name = ""
port_desc = ""

print("\nAvailable Ports:\n")
for port, desc, hwid in serial.tools.list_ports.comports():
    print("{} : {} [{}]".format(port, desc, hwid))
    if "openmv" in desc.lower():
        if port_name == '':
            port_name = port
            port_desc = desc
        else:
            port_name = '?'
            port_desc = ''

if "openmv" not in port_desc.lower():
    sys.stdout.write("\nPlease enter a port name: ")
    port_name = input()

print(port_name)
sys.stdout.flush()

try:
    interface = rpc.rpc_usb_vcp_master(port_name)
    pass
except serial.serialutil.SerialException as err:
    print(err)
    print("Press Enter to continue")
    input()
    exit(0)
print("")
sys.stdout.flush()

# Uncomment the below line to setup your OpenMV Cam for controlling over WiFi.
#
# * slave_ip - IP address to connect to.
# * my_ip - IP address to bind to ("" to bind to all interfaces...)
# * port - Port to route traffic to.
#
# interface = rpc.rpc_network_master(slave_ip="xxx.xxx.xxx.xxx", my_ip="", port=0x1DBA)

take_thr_from_cam = True
unikostyl.take_thr_from_cam = False


# This will be called with the bytes() object generated by the slave device.
def jpg_frame_buffer_cb(data):
    global take_thr_from_cam
    
    cam_thr = str(data[:300])
    #print(cam_thr, len(cam_thr))
    if take_thr_from_cam:
        take_thr_from_cam = False
        cam_thr = cam_thr[cam_thr.find('['):cam_thr.rfind(']') + 1]
        print(cam_thr)
        unikostyl.thresholds = eval(cam_thr)

    data = data[300:]
    #print(cam_thr, len(cam_thr))
    print(len(cam_thr))

    try:
        image = Image.open(io.BytesIO(data)) #'tomsk.bmp'
    except Exception as exc:
        print(exc)
        return
    
    unikostyl.main_loop_frame(image_pixels=np.rot90(np.array(image), k=1))


def save_thr_to_camera():
    unikostyl.save_thr = False
    with open("thresholds.txt", "w") as file:
        file.write(str(list(unikostyl.thresholds)))
    print('SAVE')
    result = interface.call("save_thresholds", str(unikostyl.thresholds))
    if result is None:
        print('FAILED TO SAVE')
    else:
        print(str(bytes(result)))


unikostyl.save_to_camera = save_thr_to_camera
base_cam_arguments = "sensor.RGB565;sensor.QQVGA"
print(base_cam_arguments)
while(True):
    sys.stdout.flush()

    # You may change the pixformat and the framesize of the image transferred from the remote device
    # by modifying the below arguments.
    msg = base_cam_arguments + ";"
    result = interface.call("jpeg_image_stream", msg)
    print('connecting... send', msg)
    if result is not None:
        # THE REMOTE DEVICE WILL START STREAMING ON SUCCESS. SO, WE NEED TO RECEIVE DATA IMMEDIATELY.
        interface.stream_reader(jpg_frame_buffer_cb, queue_depth=8)

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            quit()
